### ISSUE TITLE
Move from a text spec file to a json file

### ISSUE THREAD

**Issue by pathikrit** [DamonOehlman/testrest#8]
.txt based spec file seems unstructured. What about something like this:

``` javascript
[
  {
    "title": "test1",
    "method": "GET",
    "resource": "/path",
    "expected": {
      "name": "Pathikrit Bhowmick"
       "sex": "lots"
    }
  },

  {
    "title": "test2 - invalid route",
    "method": "GET",
    "resource": "/damn/you",
    "status": 4xx
  }
]
```

**Comment by DamonOehlman** [comment]
@pathikrit This is definitely something that I could implement in addition to the .txt file spec that I mostly use.  If there is enough demand for the feature then I'll definitely make it happen.  I'll post a tweet to this issue and see what others think, and if they have any ideas for a JSON format that they would like to use prior to doing any implementation work.

**Comment by pathikrit** [comment]
Cool! Nice thing about JSONs is you don't need separate parsers in your code and the keys of the spec.json could be the same option keys that the request library takes in

**Comment by DamonOehlman** [comment]
@pathikrit I've changed things up a fair bit for the 0.5.x release and have took into your consideration the suggestion with regards to JSON.  You can now choose to use either JSON or YAML to define tests and so far it feels pretty easy to work with.

The best example of this (at the moment) can be found in the test suite.  A good example is this simple test which tests that the JSON + YAML versions of the file exhibit the same behaviour:

https://github.com/DamonOehlman/testrest/blob/master/test/simple.js

I've got a fair bit of doco to write, but hopefully I'll nail that over the next couple of days.  If you've got any questions feel free to let me know.

Cheers,
Damon.

**Comment by pathikrit** [comment]
Looks good - JSON/YAML are definitely better IMO than a .txt file because of the structure. If you want a cleaner syntax like yaml AND want the tests itself to have expressions then you can use CoffeeScript maybe e.g:

``` coffeescript
  title: "test2 - invalid route"
  method: "GET"
  resource: "/damn/you"
  status: if process.env is 'test' then "4xx"  else '3xx'
```
